# check for updates in dependencies
# docs: https://dependabot.com/docs/config-file
# enable auto-merge for security patches
version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "[dependabot]"
    default_reviewers:
      - "r0bb3n"
    default_assignees:
      - "r0bb3n"
    allowed_updates:
      - match:
          dependency_type: "all"
          # Supported dependency types:
          # - "development"
          #   Development dependency group (supported by some package managers)
          # - "production"
          #   Production dependency group (supported by some package managers)
          # - "direct"
          #   Direct/top-level dependencies
          # - "indirect"
          #   Indirect/transient/sub-dependencies
          # - "all"
          update_type: "all"
          # Supported update types:
          # - "security"
          # - "all"
    automerged_updates:
      - match:
          dependency_type: "all"
          # Supported dependency types:
          # - "development"
          # - "production"
          # - "all"
          update_type: "security:patch"
          # Supported updates to automerge:
          # - "security:patch"
          #   SemVer patch update that fixes a known security vulnerability
          # - "semver:patch"
          #   SemVer patch update, e.g. > 1.x && 1.0.1 to 1.0.3
          # - "semver:minor"
          #   SemVer minor update, e.g. > 1.x && 2.1.4 to 2.3.1
          # - "in_range"
          #   matching the version requirement in your package manifest
          # - "all"