# This workflow will check the dependencies with OWASP

name: OWASP Dependency Checker

on:
  schedule:
    - cron:  '42 5 * * 5'
#    - cron:  '40 11 1 4 *'

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Checkout `latest` tag
        uses: actions/checkout@v2
        with:
          ref: latest
      - name: Run OWASP Dependency Checker for `latest`
        # don't run for version 1.0.2 since it has no proper profile
        env:
          POM_V102_HASH: 026b2554c3d5788bb55d2e70d41ec92c7d530138d8586d1f3ee0fd16e4e95662
          POM_THIS_HASH: ${{ hashFiles('pom.xml') }}
        run: |
          if [[ "$POM_THIS_HASH" == "$POM_V102_HASH" ]]
          then
            echo "::warning file=pom.xml::pom.xml of latest tag is from version 1.0.2, which does not support the required profile. Skipping check."
            exit 0
          fi
          mvn --file pom.xml --batch-mode \
            dependency-check:check -P vuln-check
      - name: Upload dependency report for latest tag
        uses: actions/upload-artifact@v1.0.0
        with:
          name: dep-report-latest
          path: target/dependency-check-report.html
      - name: Checkout `master` branch
        uses: actions/checkout@v2
        with:
          ref: master
          clean: true
      - name: Run OWASP Dependency Checker for `master`
        run: |
          mvn --file pom.xml --batch-mode \
            dependency-check:check -P vuln-check
      - name: Upload dependency report for master branch
        uses: actions/upload-artifact@v1.0.0
        with:
          name: dep-report-master
          path: target/dependency-check-report.html
