# This workflow will check the dependencies with OWASP

name: OWASP Dependency Checker

on:
  schedule:
#    - cron:  '42 5 * * 5'
    - cron:  '7 9 1 4 *'

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Checkout `latest` tag
        uses: actions/checkout@v2
        with:
          ref: latest
      - name: Run OWASP Dependency Checker for `latest`
        run: mvn --file pom.xml --batch-mode dependency-check:check -P vuln-check
      - name: Checkout `master` branch
        uses: actions/checkout@v2
        with:
          ref: master
          clean: true
      - name: Run OWASP Dependency Checker for `master`
        run: mvn --file pom.xml --batch-mode dependency-check:check -P vuln-check
